all:
	@echo clean: removes intermediate results

clean:
	cd glsim; make clean; cd ..
	cd glsta; make clean; cd ..
	cd layout; make clean; cd ..
	cd sim; make clean; cd ..
	cd sta; make clean; cd ..
	cd syn; make clean; cd ..
